#!/bin/bash

# Update package list
sudo apt update -y

# Install ssh server on ubuntu
sudo apt install openssh-server
sudo systemctl start ssh -y
sudo systemctl enable --now ssh
sudo ufw allow ssh

# Install Apache
sudo apt install -y apache2

# Start Apache service
sudo systemctl start apache2

# Enable Apache to start on boot
sudo systemctl enable apache2

# Open firewall
ufw allow 'Apache'
ufw enable

# Create index.html
echo "<h1>Hello World from C-DAC, Pune</h1>" > /var/www/html/index.html










#!/bin/bash
# 1. Update system package repository
sudo apt update -y

# 2. Install Apache web server 
sudo apt install -y apache2

# 3. Create the web page with your exact custom text
echo "<h1>Hello World from C-DAC, Pune</h1>" | sudo tee /var/www/html/index.html

# 4. Ensure Apache is running and active
sudo systemctl enable --now apache2

